### ISSUE TITLE
Double-clicking a closed tab's result does not reopen the tab

### ISSUE THREAD

**Issue by jackusay** [jackusay/cuda_find_in_filesJ#15]
If you search a word, then close the tab (the note), and double click the word's result in bottom window, it will show error.

error in console:

```
Traceback (most recent call last):
  File "C:\Users\chek\Downloads\app note\cudatext-windows-i386-1.188.0.0\py\cudatext.py", line 1256, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "C:\Users\chek\Downloads\app note\cudatext-windows-i386-1.188.0.0\py\cuda_find_in_filesJ\bottom_panel.py", line 229, in ed_click_dbl
    ed.set_caret(main_x, main_y, main_x+len_x, main_y) #select keyword
AttributeError: 'NoneType' object has no attribute 'set_caret'
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: AttributeError: 'NoneType' object has no attribute 'set_caret'
```

**Comment by jackusay** [comment]
check bottom_panel.py https://github.com/jackusay/cuda_find_in_filesJ/blob/f1e282b765aada7091f5c4778b4fe02806cb06b2/bottom_panel.py#L207

**Comment by jackusay** [comment]
ref
https://github.com/Alexey-T/CudaText/discussions/5698
https://github.com/kvichans/cuda_find_in_files4/issues/82#issuecomment-2095775085

**Comment by jackusay** [comment]
fix https://github.com/jackusay/cuda_find_in_filesJ/commit/935c879866fd73471523061775f5c047079a2976
